config/routes.rb
Rails.application.routes.draw do
  resources :bookings
# user
 get '/', to: 'users#index'
 post '/users', to: 'users#create'
 get '/users/:id', to: 'users#show'
 patch '/users/:id', to: 'users#update'
delete '/users/:id', to: 'users#destroy'
# session
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
# message
  get '/messages', to: 'messages#index'
  post '/messages', to: 'messages#create'
  delete '/messages/:id', to: 'messages#destroy'
# events
  get '/events', to: 'events#index'
  get '/events/:id',to: 'events#show'
  post 'events', to: 'events#create'
  delete '/events/:id', to: 'events#destroy'
  patch '/events/:id', to: 'events#update'
  post '/events/:id/like', to: 'events#like', as: 'like_event'
# bookings
    post 'bookings', to: 'bookings#create'
    get '/bookings/user/:user_id', to: 'bookings#user_bookings', as: 'user_bookings'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authorized, only: [:create, :index, :user_bookings]

def index
    render json: Booking.all
end

def create
  booking = Booking.create(booking_params)
  if booking.valid?
    render json: { booking: booking, status: :created }
  else
    render json: { error: booking.errors.full_messages.to_sentence }, status: :unprocessable_entity
  end
end



 def user_bookings
  user = User.find(params[:id])
  if user
    bookings = user.bookings
    render json: bookings
  else
    render json: { error: 'User not found' }, status: :not_found
  end
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.permit(:user_id, :event_id, :total, :tickets)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>User:</strong>
    <%= booking.user_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= booking.event_id %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= booking.total %>
  </p>

  <p>
    <strong>Tickets:</strong>
    <%= booking.tickets %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :event_id, style: "display: block" %>
    <%= form.text_field :event_id %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.number_field :total %>
  </div>

  <div>
    <%= form.label :tickets, style: "display: block" %>
    <%= form.number_field :tickets %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>